# Generated by Django 6.0.6 on 2026-06-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Check to hide this note from your main view without completely deleting it'),
        ),
        migrations.AddField(
            model_name='notes',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='Check to keep this note prioritized at the top of your dashboard'),
        ),
        migrations.AddField(
            model_name='notes',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', help_text='Tracks whether the note is a work-in-progress draft or ready for display', max_length=10),
        ),
    ]
